[package]
name = "smcrypt"
version = "0.1.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"

[dependencies]
crypto_box = "0.5.0"
base64 = "0.13.0"
rand = "0.7.3"
nanoserde = "0.1"
